// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/uscms_data/d3/sdurgut/RESEARCH/CMSSW_5_3_7_patch5/src/Analysis/FourMuonPAT/test/AnalysisFinal/EvtMixing/AutoDict_vector_TLorentzVector_.cxx";

#endif
